### ISSUE TITLE
Change log

### ISSUE THREAD

**Issue by strugee** [creationix/step#54]
This project really needs a change log.

See http://keepachangelog.com

**Comment by creationix** [comment]
You're welcome to add one in a PR. :)

**Comment by strugee** [comment]
@creationix great, working on it now. As a side note, did you know that 0.0.6 was released on 06/06 2015? :P

**Comment by creationix** [comment]
I'd believe it.

**Comment by strugee** [comment]
Lol, I amended the commit so it'd auto-close this issue but apparently you'd already merged! :P
