### ISSUE TITLE
Please release 1.0.0 to npm

### ISSUE THREAD

**Issue by strugee** [creationix/step#55]
The semantic versioning specification [states][1]:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

However, in step's case, this isn't really accurate. At a certain point a project has been around long enough that it should be considered stable. Any future changes can be made in semver-major releases. (Also consider - especially for a smaller library like step, semi-frequent semver-major changes aren't the end of the world. They just aren't.)

Please publish 1.0.0 to npm to indicate that step is at least a somewhat mature project.

 [1]: http://semver.org/#spec-item-4

**Comment by creationix** [comment]
Good idea, let's do this once the changelog is added.

**Comment by creationix** [comment]
Done
